# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0002_cie_distrito_establecimientosalud_niveleconomico_seguro_sexo_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('cie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Cie')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Distrito')),
                ('eess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.EstablecimientoSalud')),
                ('niveleconomico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.NivelEconomico')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Seguro')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Sexo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Zona')),
            ],
        ),
    ]
