# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0003_situacionsalud'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacionsalud',
            name='distritoden',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='situacionsalud',
            name='sexoden',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
