# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0004_auto_20171212_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacionsalud',
            name='cie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Cie'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Distrito'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='eess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.EstablecimientoSalud'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='niveleconomico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.NivelEconomico'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Seguro'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Sexo'),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SituacionSalud.Zona'),
        ),
    ]
