# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0005_auto_20171212_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
