# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0006_auto_20171212_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cie',
            name='id',
        ),
        migrations.AlterField(
            model_name='cie',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
