# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0007_auto_20171212_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionsalud',
            name='eess',
        ),
        migrations.DeleteModel(
            name='EstablecimientoSalud',
        ),
    ]
