# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0008_auto_20171212_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoSalud',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=210)),
            ],
        ),
    ]
