# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0011_remove_situacionsalud_sexoden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionsalud',
            name='distritoden',
        ),
    ]
