# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 01:11
from __future__ import unicode_literals

import SituacionSalud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionSalud', '0012_remove_situacionsalud_distritoden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2)),
                ('edad', models.IntegerField()),
                ('nomenclaturar', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sexo',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='situacionsalud',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name=SituacionSalud.models.Edad),
        ),
    ]
